// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveySample.Infrastructure;

#nullable disable

namespace SurveySample.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230926085927_InitalDb")]
    partial class InitalDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveySample.Domain.Entities.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("surveyId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("surveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SurveySample.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("optionText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("questionId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("questionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("SurveySample.Domain.Entities.Survey", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("surveyTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SurveySample.Domain.Entities.Question", b =>
                {
                    b.HasOne("SurveySample.Domain.Entities.Survey", null)
                        .WithMany("questions")
                        .HasForeignKey("surveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SurveySample.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("SurveySample.Domain.Entities.Question", null)
                        .WithMany("questionOptions")
                        .HasForeignKey("questionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SurveySample.Domain.Entities.Question", b =>
                {
                    b.Navigation("questionOptions");
                });

            modelBuilder.Entity("SurveySample.Domain.Entities.Survey", b =>
                {
                    b.Navigation("questions");
                });
#pragma warning restore 612, 618
        }
    }
}
